// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plooto.Assessment.Payment.Infrastructure;

#nullable disable

namespace Plooto.Assessment.Payment.API.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20230930200938_schema_update")]
    partial class schema_update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Plooto Default");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2023, 9, 30, 20, 9, 38, 687, DateTimeKind.Unspecified).AddTicks(4819), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("_dueDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DueDate");

                    b.Property<int>("_identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_identifier"), 1L, 1);

                    b.Property<decimal>("_previousBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PreviousBalance");

                    b.Property<decimal>("_totalDue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalDue");

                    b.Property<string>("_vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vendor");

                    b.HasKey("Id");

                    b.ToTable("Bills", "billing");
                });

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.PaymentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BillId");

                    b.Property<Guid?>("BillId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Plooto Default");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2023, 9, 30, 20, 9, 38, 683, DateTimeKind.Unspecified).AddTicks(5316), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTimeOffset>("_debitDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DebitDate");

                    b.Property<int>("_identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_identifier"), 1L, 1);

                    b.Property<int>("_method")
                        .HasColumnType("int")
                        .HasColumnName("Method");

                    b.Property<string>("_status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("BillId1");

                    b.ToTable("Payments", "billing");
                });

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.PaymentDetail", b =>
                {
                    b.HasOne("Plooto.Assessment.Payment.Domain.Bill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plooto.Assessment.Payment.Domain.Bill", null)
                        .WithMany("BillPayments")
                        .HasForeignKey("BillId1");
                });

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.Bill", b =>
                {
                    b.Navigation("BillPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
