// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plooto.Assessment.Payment.Infrastructure;

#nullable disable

namespace Plooto.Assessment.Payment.API.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20230930223548_add_bill_status")]
    partial class add_bill_status
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Plooto Default");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2023, 9, 30, 22, 35, 48, 190, DateTimeKind.Unspecified).AddTicks(3569), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("_billStatusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("_dueDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DueDate");

                    b.Property<int>("_identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_identifier"), 1L, 1);

                    b.Property<decimal>("_previousBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PreviousBalance");

                    b.Property<decimal>("_totalDue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalDue");

                    b.Property<string>("_vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vendor");

                    b.HasKey("Id");

                    b.HasIndex("_billStatusId");

                    b.ToTable("Bills", "billing");
                });

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.BillStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("BillStatus", "billing");
                });

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.PaymentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BillId")
                        .HasColumnOrder(6);

                    b.Property<Guid?>("BillId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Plooto Default");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2023, 9, 30, 22, 35, 48, 187, DateTimeKind.Unspecified).AddTicks(7255), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("_debitDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DebitDate")
                        .HasColumnOrder(3);

                    b.Property<int>("_identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identifier")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_identifier"), 1L, 1);

                    b.Property<int>("_method")
                        .HasColumnType("int")
                        .HasColumnName("Method")
                        .HasColumnOrder(5);

                    b.Property<string>("_status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("BillId1");

                    b.ToTable("Payments", "billing");
                });

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.Bill", b =>
                {
                    b.HasOne("Plooto.Assessment.Payment.Domain.BillStatus", "BillStatus")
                        .WithMany()
                        .HasForeignKey("_billStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillStatus");
                });

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.PaymentDetail", b =>
                {
                    b.HasOne("Plooto.Assessment.Payment.Domain.Bill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plooto.Assessment.Payment.Domain.Bill", null)
                        .WithMany("BillPayments")
                        .HasForeignKey("BillId1");
                });

            modelBuilder.Entity("Plooto.Assessment.Payment.Domain.Bill", b =>
                {
                    b.Navigation("BillPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
